## Imports

In [10]:
from sklearn.cluster import MiniBatchKMeans
from sklearn.datasets import load_iris
import numpy as np
import cv2

## Iris

In [2]:
data = load_iris()

In [4]:
X = data.data
y = data.target
y_names = data.target_names

In [151]:
print('X =>', X)
print('y =>', y)
print('y_names =>', y_names)

X => [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3

## Incremental Clustering for IRIS dataset

In [152]:
minibatchKmeans = MiniBatchKMeans(n_clusters=3,random_state=0,batch_size=6)

In [116]:
minibatchKmeans.fit(X)

In [9]:
y_pred = minibatchKmeans.predict(X)

In [154]:
print("accuracy:", (1-(np.count_nonzero(y_pred == y) / len(y))) * 100)

accuracy: 91.33333333333333


## Intrusion Detection

In [145]:
def detect():
    font = cv2.FONT_HERSHEY_SIMPLEX
    cam = cv2.VideoCapture(1)
    cam.set(3, 640)
    cam.set(4, 480)
    image_list = []
    count = 0
    
    while(True):
        ret, img = cam.read()
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        if count >= 1:
            temp = res_list
        minibatchKmeans = MiniBatchKMeans(n_clusters=3,random_state=0)
        res_list = minibatchKmeans.fit(gray)
        if count < 1:
            temp = res_list
        count+=1
        pred = temp.predict(gray)
        
        if False in (temp.labels_ == pred):
            cv2.putText(img, "Detected", (320, 240), font, 1, (255,255,255), 2)
        else:
            cv2.putText(img, "Clean", (320, 240), font, 1, (255,255,255), 2)
            
        cv2.imshow('image', img)
        k = cv2.waitKey(100) & 0xff
        if k == 27:
            break
    cam.release()
    cv2.destroyAllWindows()        

In [146]:
detect()

## Extras

In [138]:
minibatchKmeans = MiniBatchKMeans(n_clusters=3,random_state=0)

In [139]:
image1 = cv2.imread('1.jpg')
gray1 = cv2.cvtColor(image1, cv2.COLOR_BGR2GRAY)
image2 = cv2.imread('2.jpg')
gray2 = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)
res_list = minibatchKmeans.fit(gray1) #static
pred = minibatchKmeans.predict(gray2) #with person

In [140]:
False in (res_list.labels_ == pred)

True

In [141]:
res_list.labels_ == pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,